### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv' - slack-starterbot

### ISSUE THREAD

**Issue by underrtow** [mattmakai/fullstackpython.com#155]
Hi,

Thanks a lot for the bot - I've copied the code (using Python 3.6.4) and originally received error as follows:

Traceback (most recent call last):
File "c:\Bot\starterbot\lib\site-packages\slackclient\client.py", line 52, in rtm_connect
self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
File "c:\Bot\starterbot\lib\site-packages\slackclient\server.py", line 85, in rtm_connect
raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
Connection failed. Exception traceback printed above.

I've managed to work it around by removing argument (with_team_state=False):

But now I receive following error:

File "starterbot3.py", line 66, in 
command, channel = parse_bot_commands(slack_client.rtm_read())
File "c:\Bot\starterbot\lib\site-packages\slackclient\client.py", line 135, in rtm_read
json_data = self.server.websocket_safe_read()
File "c:\Bot\starterbot\lib\site-packages\slackclient\server.py", line 194, in websocket_safe_read
data += "{0}\n".format(self.websocket.recv())
AttributeError: 'NoneType' object has no attribute 'recv'

Any idea how to handle?

**Comment by mattmakai** [comment]
hmm.. looks like the bot may not be authenticated correctly? I see the slackclient.server.SlackLoginError there

**Comment by underrtow** [comment]
Yeah, so it seems bug in Python 3.6.4 with tcp was causing it. Downgraded to 3.6.3 and works like a charm. Thanks!
